### ISSUE TITLE
When run import angr, error occurs

### ISSUE THREAD

**Issue by vancaho** [angr/archinfo#1]
Hi I try to compile pyvex on windows platform myself. Then after I run "import angr", there are errors in the arch.py:

>>> import angr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\angr\__init__.py", line 7, in <module>
    from .project import *
  File "C:\Python27\lib\site-packages\angr\project.py", line 10, in <module>
    import cle
  File "C:\Python27\lib\site-packages\cle\__init__.py", line 6, in <module>
    from .loader import *
  File "C:\Python27\lib\site-packages\cle\loader.py", line 688, in <module>
    from .tls import TLSObj
  File "C:\Python27\lib\site-packages\cle\tls.py", line 4, in <module>
    from .backends import Backend
  File "C:\Python27\lib\site-packages\cle\backends\__init__.py", line 4, in <mod
ule>
    import archinfo
  File "C:\Python27\lib\site-packages\archinfo\__init__.py", line 2, in <module>

    from .arch import *
  File "C:\Python27\lib\site-packages\archinfo\arch.py", line 320, in <module>
    ArchAMD64(), ArchX86(),
  File "C:\Python27\lib\site-packages\archinfo\arch_amd64.py", line 10, in __ini
t__
    super(ArchAMD64, self).__init__(endness)
  File "C:\Python27\lib\site-packages\archinfo\arch.py", line 19, in __init__
    self.vex_archinfo = self.vex_archinfo.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

My operation system is Windows 7 32bit. How to solve this problem?

Thanks very much

**Comment by ronnychevalier** [comment]
It's fixed, it will be in this repo in a couple of days.

**Comment by zardus** [comment]
Yep, sorry about that! We've been swamped with a combination of deadlines and haven't had a chance to push the latest updates. There are a *lot*, including this fix.

**Comment by ekse** [comment]
This issue can probably be closed now?

**Comment by zardus** [comment]
Good call!
