### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by fabaff** [angr/archinfo#112]
Starting with `9.1.12332` it's no longer possible to import `archinfo` at least on `x86_64`. The issue can be reproduced in a clean `venv` with the a new clone. 

```bash
$ git clone git@github.com:angr/archinfo.git
Cloning into 'archinfo'...
remote: Enumerating objects: 2688, done.
remote: Counting objects: 100% (537/537), done.
remote: Compressing objects: 100% (239/239), done.
remote: Total 2688 (delta 383), reused 440 (delta 298), pack-reused 2151
Receiving objects: 100% (2688/2688), 573.72 KiB | 1.76 MiB/s, done.
Resolving deltas: 100% (1893/1893), done.
[fabaff@test-py repos]$ cd archinfo/
[fabaff@test-py archinfo]$ python -m venv .
[fabaff@test-py archinfo]$ source bin/activate
(archinfo) [fabaff@test-py archinfo]$ python setup.py develop
/home/fabaff/Documents/repos/archinfo/lib64/python3.10/site-packages/setuptools/dist.py:498: UserWarning: The version specified ('9.1.gitrolling') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
[...]
Finished processing dependencies for archinfo===9.1.gitrolling
(archinfo) [fabaff@test-py archinfo]$ python3
Python 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import archinfo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fabaff/Documents/repos/archinfo/archinfo/__init__.py", line 26, in <module>
    from .arch_amd64    import ArchAMD64
  File "/home/fabaff/Documents/repos/archinfo/archinfo/arch_amd64.py", line 378, in <module>
    register_arch([r'.*amd64|.*x64|.*x86_64|.*metapc'], 64, Endness.LE, ArchAMD64)
  File "/home/fabaff/Documents/repos/archinfo/archinfo/arch.py", line 800, in register_arch
    all_arches.append(my_arch(endness))
  File "/home/fabaff/Documents/repos/archinfo/archinfo/arch_amd64.py", line 68, in __init__
    self.reg_blacklist.append(register.name)
AttributeError: 'NoneType' object has no attribute 'append'
>>> 
```

**Comment by ltfish** [comment]
Fixed. Thank you!
