### ISSUE TITLE
Vanilla `archinfo` seems to have dependencies problem

### ISSUE THREAD

**Issue by Pamplemousse** [angr/archinfo#94]
### 1. missing `unicorn`

A minimal working example; Using the following:

```shell
$ mkvirtualenv test_issue
$ source ~/.virtualenvs/test_issue/bin/activate
(test_issue)$ pip install archinfo
(test_issue)$ python
>>> import archinfo
```

... triggers:

```
Traceback (most recent call last):                                                                                                                                       
  File "<stdin>", line 1, in <module>                                               
  File "/home/pamplemousse/Workspace/angr/archinfo/archinfo/__init__.py", line 28, in <module>             
    from .arch_arm      import ArchARM, ArchARMEL, ArchARMHF, ArchARMCortexM                                                                                             
  File "/home/pamplemousse/Workspace/angr/archinfo/archinfo/arch_arm.py", line 42, in <module>       
    class ArchARM(Arch):                                                                                                                                                 
  File "/home/pamplemousse/Workspace/angr/archinfo/archinfo/arch_arm.py", line 187, in ArchARM     
    uc_mode_thumb = _unicorn.UC_MODE_LITTLE_ENDIAN + _unicorn.UC_MODE_THUMB                                                                                              
AttributeError: 'NoneType' object has no attribute 'UC_MODE_LITTLE_ENDIAN'
```

This could probably be fixed by adding the right dependency into `setup.py`.

### 2. missing `pyvex` :confused:

From the previous example:

```shell
(test_issue)$ pip install unicorn==1.0.2rc4
(test_issue)$ python
>>> import archinfo
```

... triggers the following:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pamplemousse/Workspace/angr/archinfo/archinfo/__init__.py", line 26, in <module>
    from .arch_amd64    import ArchAMD64
  File "/home/pamplemousse/Workspace/angr/archinfo/archinfo/arch_amd64.py", line 359, in <module>
    register_arch([r'.*amd64|.*x64|.*x86_64|.*metapc'], 64, Endness.LE, ArchAMD64)
  File "/home/pamplemousse/Workspace/angr/archinfo/archinfo/arch.py", line 819, in register_arch
    all_arches.append(my_arch(endness))
  File "/home/pamplemousse/Workspace/angr/archinfo/archinfo/arch_amd64.py", line 44, in __init__
    super(ArchAMD64, self).__init__(endness)
  File "/home/pamplemousse/Workspace/angr/archinfo/archinfo/arch.py", line 281, in __init__
    for reg_name in self.artificial_registers:
AttributeError: 'ArchAMD64' object has no attribute 'artificial_registers'
```

In the `archinfo/arch.py`, the code declaring `self.artificial_registers` is inside an branch where `_pyvex` is not `None`. But its use line 281 is not.

Sadly, this seems a bit trickier to fix than the previous one: `archinfo` is a dependency of `pyvex`; So, adding `pyvex` as a dependency of `archinfo` would create a cyclic dependency...

**Comment by rhelmot** [comment]
Fixed both. In general, archinfo is supposed to have a "weak dependency" on pyvex/capstone/unicorn/keystone, which means that it doesn't list the dependency and works fine if it's not installed, but will take on extra behaviors if it is installed.
